os: linux
dist: focal
language: python
python:
  - "3.9"

# Cache PlatformIO packages using Travis CI container-based infrastructure
cache:
  directories:
    - "~/.platformio"
    - $HOME/.cache/pip

install:
  - pip install -U platformio
  - pio update
  - platformio lib install 64

script:
  - pio ci --board=esp32dev  --lib="."
